addons:
    hosts:
        - mysql

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    
services:
    - mysql
  
before_script:
    - composer install --prefer-source
    - mysql -e 'create database tree;'

script:
    - vendor/bin/codecept run